name: Lint
on: [push]
jobs:
  lint:
    name: Run eslint on ${{ matrix.node }} and ${{ matrix.os }}
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@2.1
        with: 
          version: 6

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install deps and build (with cache)
        run: pnpm i --frozen-lockfile

      - name: Run lint script
        run: pnpm lint
